DROP TABLE IF EXISTS `client` CASCADE;
CREATE TABLE  client (
    id BIGINT NOT NULL AUTO_INCREMENT,
    dob DATE,
    email VARCHAR(255) NOT NULL UNIQUE ,
    name VARCHAR(255) NOT NULL ,
    PRIMARY KEY (id))